package com.codecrafthub.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Represents a course stored in courses.json.
 * Jackson maps camelCase Java fields to snake_case JSON names where noted.
 */
public class Course {

    /** Unique identifier, auto-generated by the service (starts at 1). */
    private Long id;

    /** Display name of the course (required). */
    private String name;

    /** Short summary of what the course covers (required). */
    private String description;

    /** Target completion date in YYYY-MM-DD format (required in requests). */
    @JsonProperty("target_date")
    private LocalDate targetDate;

    /**
     * Current progress state (required).
     * Must be exactly: "Not Started", "In Progress", or "Completed".
     */
    private String status;

    /** Timestamp when the course was created (auto-generated, response only). */
    @JsonProperty("created_at")
    private LocalDateTime createdAt;

    public Course() {
        // Default constructor required by Jackson for deserialization
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDate getTargetDate() {
        return targetDate;
    }

    public void setTargetDate(LocalDate targetDate) {
        this.targetDate = targetDate;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
